name: Build VuePress Static Pages
on:
    workflow_dispatch:
    push:
        branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with: 
          fetch-depth: 0

      - name: Install and Build 🔧
        run: |
          yarn
          yarn build
          
      - name: Install qshell
        run: 
          - wget https://devtools.qiniu.com/qshell-v2.6.3-linux-amd64.tar.gz
          - tar -xzf qshell-v2.6.3-linux-amd64.tar.gz
          
      - name: Configure qshell
        env:
          SECRET_ID: ${{ secrets.QiNiu_AK }}
          SECRET_KEY: ${{ secrets.QiNiu_SK }}
        run: ./qshell account $SECRET_ID $SECRET_KEY jjun

      - name: Upload
        run: 
          - ./qshell listbucket site-imjz -o list.txt
          - ./qshell batchdelete --force site-imjz -i list.txt
          - ./qshell qupload2 --bucket site-imjz --overwrite --src-dir dist
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-page
          folder: dist
