name: Build VuePress Static Pages
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-page
        FOLDER: dist
        BUILD_SCRIPT: yarn && yarn build
